### ISSUE TITLE
not able to find hawq-hadoop 

### ISSUE THREAD

**Issue by SaiSharathReddy** [kdunn926/sparkHawq#1]
Hi 

I was not able find hawq-hadoop library can I know the location from where I can access it.

**Comment by kdunn926** [comment]
It looks like you'll need to checkout the [incubator-hawq](https://github.com/apache/incubator-hawq) repo then `mvn package install -DskipTests ` [these](https://github.com/apache/incubator-hawq/tree/master/contrib/hawq-hadoop) libraries into a local Maven repo.  I've updated the [docs](https://github.com/kdunn926/spark-hawq#build-hawq-dependencies) to help get things compiling again. Enjoy!
